FROM node:20-alpine

WORKDIR /app

# Configurar cache do npm
ENV NPM_CONFIG_CACHE=/tmp/npm-cache

# Instalar dependências
COPY package*.json ./
RUN npm install

# Copiar código fonte
COPY . .

# Expor a porta de desenvolvimento
EXPOSE 5173

# Comando para desenvolvimento
CMD ["npm", "run", "dev"] 